{"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/Barcode","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/Detection","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/DetectionFilter","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/EdgeOCR","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/License","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/LicenseBuilder","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/ModelBuilder","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/ModelSettings","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/ScanResult","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/Text","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/TextMapper"]},{"title":"Protocols","identifiers":["doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/EdgeVisionAPI","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/NefrockLicenseAPI"]},{"identifiers":["doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/BBoxTextDetectorSettings","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/CropRect","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/DBTextDetectorSettings","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/ExecutionSettings","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/Model","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/ModelInformation","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/ScanOptions"],"title":"Structures"},{"title":"Enumerations","identifiers":["doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/BarcodeFormat","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/DBPostProcessing","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/DetectionType","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/EdgeError","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/ExecutionDevice","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/Rotation","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/ScanConfirmationStatus"]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/edgeocrswift"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/edgeocrswift"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"content":[{"text":"Overview","anchor":"Overview","type":"heading","level":2}],"kind":"content"}],"hierarchy":{"paths":[[]]},"sections":[],"metadata":{"roleHeading":"Framework","modules":[{"name":"EdgeOCRSwift"}],"externalID":"EdgeOCRSwift","title":"EdgeOCRSwift","symbolKind":"module","role":"collection"},"references":{"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/ScanConfirmationStatus":{"abstract":[{"type":"text","text":"スキャン結果の確定状態を表す列挙型"}],"role":"symbol","navigatorTitle":[{"text":"ScanConfirmationStatus","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanConfirmationStatus"}],"kind":"symbol","identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/ScanConfirmationStatus","type":"topic","url":"\/documentation\/edgeocrswift\/scanconfirmationstatus","title":"ScanConfirmationStatus"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/Rotation":{"identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/Rotation","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Rotation"}],"url":"\/documentation\/edgeocrswift\/rotation","navigatorTitle":[{"text":"Rotation","kind":"identifier"}],"title":"Rotation","type":"topic","abstract":[{"text":"画像の回転角度を表す列挙型","type":"text"}],"kind":"symbol"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/LicenseBuilder":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LicenseBuilder"}],"url":"\/documentation\/edgeocrswift\/licensebuilder","identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/LicenseBuilder","title":"LicenseBuilder","abstract":[{"type":"text","text":"ライセンス認証APIのビルダークラスです．"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"LicenseBuilder"}],"kind":"symbol"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/ModelInformation":{"kind":"symbol","identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/ModelInformation","title":"ModelInformation","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ModelInformation"}],"navigatorTitle":[{"text":"ModelInformation","kind":"identifier"}],"abstract":[{"text":"モデルの情報を保持するクラスです。","type":"text"}],"type":"topic","url":"\/documentation\/edgeocrswift\/modelinformation"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/EdgeOCRSwiftVersionNumber":{"identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/EdgeOCRSwiftVersionNumber","role":"symbol","fragments":[{"kind":"identifier","text":"EdgeOCRSwiftVersionNumber"}],"abstract":[{"text":"Project version number for EdgeOCRSwift.","type":"text"}],"type":"topic","kind":"symbol","title":"EdgeOCRSwiftVersionNumber","url":"\/documentation\/edgeocrswift\/edgeocrswiftversionnumber"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/DetectionFilter":{"identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/DetectionFilter","url":"\/documentation\/edgeocrswift\/detectionfilter","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DetectionFilter","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DetectionFilter"}],"title":"DetectionFilter","kind":"symbol"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/Barcode":{"identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/Barcode","url":"\/documentation\/edgeocrswift\/barcode","abstract":[{"text":"検出対象がバーコードの場合の検出結果を表すクラスです。","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Barcode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Barcode"}],"title":"Barcode","role":"symbol"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/ModelSettings":{"title":"ModelSettings","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ModelSettings"}],"abstract":[{"text":"モデルに関する設定を表す構造体","type":"text"}],"url":"\/documentation\/edgeocrswift\/modelsettings","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ModelSettings"}],"identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/ModelSettings","role":"symbol","type":"topic"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/ScanOptions/ScanMode":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ScanMode","kind":"identifier"}],"url":"\/documentation\/edgeocrswift\/scanoptions\/scanmode","title":"ScanOptions.ScanMode","identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/ScanOptions\/ScanMode","type":"topic","navigatorTitle":[{"text":"ScanMode","kind":"identifier"}],"abstract":[{"type":"text","text":"スキャンモードを表す列挙型です。"}],"kind":"symbol"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/ScanOptions":{"navigatorTitle":[{"kind":"identifier","text":"ScanOptions"}],"url":"\/documentation\/edgeocrswift\/scanoptions","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanOptions"}],"abstract":[{"type":"text","text":"スキャンオプションを表すクラスです。"},{"type":"text","text":" "},{"type":"text","text":"スキャンモードと切り取り範囲を指定できます。"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/ScanOptions\/ScanMode"},{"type":"text","text":" 列挙型を利用してスキャンのモードを指定します。"},{"type":"text","text":" "},{"type":"text","text":"スキャンモードは3通りあります。"}],"title":"ScanOptions","identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/ScanOptions","type":"topic"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/EdgeOCR":{"identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/EdgeOCR","navigatorTitle":[{"text":"EdgeOCR","kind":"identifier"}],"kind":"symbol","title":"EdgeOCR","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EdgeOCR","kind":"identifier"}],"url":"\/documentation\/edgeocrswift\/edgeocr"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/EdgeOCRSwiftVersionString":{"kind":"symbol","abstract":[{"text":"Project version string for EdgeOCRSwift.","type":"text"}],"url":"\/documentation\/edgeocrswift\/edgeocrswiftversionstring","fragments":[{"text":"EdgeOCRSwiftVersionString","kind":"identifier"}],"type":"topic","role":"symbol","title":"EdgeOCRSwiftVersionString","identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/EdgeOCRSwiftVersionString"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/BarcodeFormat":{"kind":"symbol","title":"BarcodeFormat","identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/BarcodeFormat","role":"symbol","abstract":[{"type":"text","text":"バーコードのフォーマットの種類を表す列挙型です。"}],"type":"topic","url":"\/documentation\/edgeocrswift\/barcodeformat","navigatorTitle":[{"text":"BarcodeFormat","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BarcodeFormat"}]},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/EdgeVisionAPI":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"EdgeVisionAPI","kind":"identifier"}],"title":"EdgeVisionAPI","role":"symbol","identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/EdgeVisionAPI","abstract":[{"type":"text","text":"EdgeVisionAPIは、EdgeOCR SDKのAPIです。"},{"text":" ","type":"text"},{"text":"EdgeOCR SDKを使用する前に、ライセンス認証を行う必要があります。","type":"text"},{"type":"text","text":" "},{"isActive":true,"identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/NefrockLicenseAPI","type":"reference"},{"type":"text","text":" を使用してライセンス認証を行ってください。"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EdgeVisionAPI"}],"type":"topic","url":"\/documentation\/edgeocrswift\/edgevisionapi"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/TextMapper":{"abstract":[],"identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/TextMapper","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextMapper"}],"title":"TextMapper","kind":"symbol","url":"\/documentation\/edgeocrswift\/textmapper","type":"topic","navigatorTitle":[{"text":"TextMapper","kind":"identifier"}]},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/ScanResult":{"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"ScanResult","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanResult"}],"title":"ScanResult","abstract":[{"text":"スキャン結果を表すクラスです。","type":"text"}],"identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/ScanResult","url":"\/documentation\/edgeocrswift\/scanresult"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/Detection":{"navigatorTitle":[{"kind":"identifier","text":"Detection"}],"type":"topic","abstract":[{"type":"text","text":"OCRエンジンの検出箇所を表すクラスです。"}],"kind":"symbol","identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/Detection","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Detection","kind":"identifier"}],"title":"Detection","role":"symbol","url":"\/documentation\/edgeocrswift\/detection"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/ExecutionSettings":{"role":"symbol","title":"ExecutionSettings","abstract":[{"type":"text","text":"エンジンの実行に関する設定を表す構造体"}],"navigatorTitle":[{"text":"ExecutionSettings","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ExecutionSettings"}],"kind":"symbol","identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/ExecutionSettings","type":"topic","url":"\/documentation\/edgeocrswift\/executionsettings"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/EdgeError":{"abstract":[{"type":"text","text":"OCRエンジンで発生したエラーを表す列挙型です。"}],"url":"\/documentation\/edgeocrswift\/edgeerror","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EdgeError","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"EdgeError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/EdgeError","title":"EdgeError"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/DBPostProcessing":{"abstract":[{"type":"text","text":"DB検出モデルにおけるポストプロセスを表す列挙型"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DBPostProcessing"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DBPostProcessing"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/DBPostProcessing","url":"\/documentation\/edgeocrswift\/dbpostprocessing","title":"DBPostProcessing"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/BBoxTextDetectorSettings":{"identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/BBoxTextDetectorSettings","url":"\/documentation\/edgeocrswift\/bboxtextdetectorsettings","role":"symbol","type":"topic","kind":"symbol","title":"BBoxTextDetectorSettings","navigatorTitle":[{"kind":"identifier","text":"BBoxTextDetectorSettings"}],"abstract":[{"type":"text","text":"BBox文字検出モデルの詳細設定"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"BBoxTextDetectorSettings","kind":"identifier"}]},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift":{"abstract":[],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift","url":"\/documentation\/edgeocrswift","title":"EdgeOCRSwift"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/License":{"identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/License","type":"topic","abstract":[],"role":"symbol","title":"License","kind":"symbol","navigatorTitle":[{"text":"License","kind":"identifier"}],"url":"\/documentation\/edgeocrswift\/license","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"License"}]},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/Model":{"url":"\/documentation\/edgeocrswift\/model","role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Model"}],"navigatorTitle":[{"text":"Model","kind":"identifier"}],"identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/Model","abstract":[{"type":"text","text":"\/\/ モデルファイルの情報を表すクラスです。"}],"kind":"symbol","title":"Model"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/CropRect":{"identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/CropRect","abstract":[{"text":"画像のスキャン範囲を表すデータクラスです。","type":"text"},{"type":"text","text":" "},{"type":"text","text":"width（height）は、入力画像の元々の幅と高さを1として切り抜かれる範囲の幅（高さ）を0.0から1.0の範囲で設定します。"},{"text":" ","type":"text"},{"text":"horizontalBias（verticalBias）は、切り抜かれる範囲の横方向（縦方向）のバイアスを0.0から1.0の範囲で設定します。","type":"text"},{"text":" ","type":"text"},{"text":"0.0の場合は切り取られる範囲の左端（上端）が画像の左端（上端）になります。","type":"text"},{"type":"text","text":" "},{"text":"1.0の場合は切り取られる範囲の右端（下端）が画像の右端（下端）になります。","type":"text"},{"type":"text","text":" "},{"text":"0.5の場合は画像の中央になります。","type":"text"},{"type":"text","text":" "},{"text":"従って、画像からはみ出る範囲を指定することはできません。","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"例えば、画像の左上から幅の50%、高さの50%の範囲を切り取る場合は、horizontalBias=0.0, verticalBias=0.0, width=0.5, height=0.5と指定します。"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CropRect"}],"url":"\/documentation\/edgeocrswift\/croprect","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CropRect"}],"title":"CropRect"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/DBTextDetectorSettings":{"navigatorTitle":[{"text":"DBTextDetectorSettings","kind":"identifier"}],"abstract":[{"type":"text","text":"DB文字検出モデルの詳細設定"}],"url":"\/documentation\/edgeocrswift\/dbtextdetectorsettings","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"DBTextDetectorSettings","kind":"identifier"}],"identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/DBTextDetectorSettings","kind":"symbol","role":"symbol","type":"topic","title":"DBTextDetectorSettings"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/ExecutionDevice":{"role":"symbol","type":"topic","title":"ExecutionDevice","kind":"symbol","identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/ExecutionDevice","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ExecutionDevice"}],"navigatorTitle":[{"text":"ExecutionDevice","kind":"identifier"}],"url":"\/documentation\/edgeocrswift\/executiondevice","abstract":[{"type":"text","text":"実行可能なデバイス"}]},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/ModelBuilder":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModelBuilder","kind":"identifier"}],"navigatorTitle":[{"text":"ModelBuilder","kind":"identifier"}],"abstract":[{"type":"text","text":"OCRエンジンを初期化するためのビルダークラスです。"},{"type":"text","text":" "},{"type":"text","text":"OCRエンジンを初期化するには、このクラスのインスタンスを作成し、"},{"type":"text","text":" "},{"type":"codeVoice","code":"fromPath"},{"text":" メソッドを呼び出して、","type":"text"},{"text":" ","type":"text"},{"text":"OCRエンジンを読み込む方法を指定した後に、","type":"text"},{"type":"codeVoice","code":"build"},{"text":"メソッドを呼び出してください","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/edgeocrswift\/modelbuilder","title":"ModelBuilder","identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/ModelBuilder"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/Text":{"url":"\/documentation\/edgeocrswift\/text","role":"symbol","type":"topic","title":"Text","navigatorTitle":[{"kind":"identifier","text":"Text"}],"identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/Text","kind":"symbol","abstract":[{"type":"text","text":"検出対象が文字列の場合の検出結果を表すクラスです。"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Text","kind":"identifier"}]},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/DetectionType":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/DetectionType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DetectionType","kind":"identifier"}],"title":"DetectionType","abstract":[{"type":"text","text":"検出結果の種類を表す列挙型"}],"navigatorTitle":[{"text":"DetectionType","kind":"identifier"}],"url":"\/documentation\/edgeocrswift\/detectiontype"},"doc://com.nefrock.EdgeOCRSwift/documentation/EdgeOCRSwift/NefrockLicenseAPI":{"title":"NefrockLicenseAPI","abstract":[{"type":"text","text":"NefrockLicenseAPIは、Nefrock OCR SDKのライセンス認証を行うためのAPIです。"},{"type":"text","text":" "},{"type":"text","text":"Nefrock OCR SDKを使用する前に、ライセンス認証を行う必要があります。"},{"type":"text","text":" "},{"type":"text","text":"ライセンス認証は、"},{"code":"activate","type":"codeVoice"},{"type":"text","text":" メソッドを使用して行います。"},{"text":" ","type":"text"},{"type":"text","text":"ライセンス認証が完了すると、"},{"code":"License","type":"codeVoice"},{"type":"text","text":" クラスのインスタンスを返します。"},{"text":" ","type":"text"},{"type":"text","text":"ライセンス認証が完了していない場合、例外が投げられます。"}],"url":"\/documentation\/edgeocrswift\/nefrocklicenseapi","kind":"symbol","identifier":"doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/NefrockLicenseAPI","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NefrockLicenseAPI","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NefrockLicenseAPI"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"title":"Variables","identifiers":["doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/EdgeOCRSwiftVersionNumber","doc:\/\/com.nefrock.EdgeOCRSwift\/documentation\/EdgeOCRSwift\/EdgeOCRSwiftVersionString"]}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}